namespace Core;

public enum UnitRace
{
    None,
    Human,
    Orc,
    Dwarf,
    NightElf,
    Undead,
    Tauren,
    Gnome,
    Troll,
    Goblin,
    BloodElf,
    Draenei,
    FelOrc,
    Naga,
    Broken,
    Skeleton,
    Vrykul,
    Tuskarr,
    ForestTroll,
    Taunka,
    NorthrendSkeleton,
    IceTroll,
    Worgen,
    GilneanHuman,
    Pandaren1,
    Pandaren2,
    Pandaren3,
    Nightborne,
    HighmountainTauren,
    VoidElf,
    LightforgedDraenei,
    ZandalariTroll,
    KulTiran,
    ThinHuman,
    DarkIronDwarf,
    Vulpera,
    MagharOrc,
    Mechagnome,
    Dracthyr1,
    Dracthyr2
}

public static class UnitRace_Extension
{
    public static string ToStringF(this UnitRace value) => value switch
    {
        UnitRace.None => nameof(UnitRace.None),
        UnitRace.Human => nameof(UnitRace.Human),
        UnitRace.Orc => nameof(UnitRace.Orc),
        UnitRace.Dwarf => nameof(UnitRace.Dwarf),
        UnitRace.NightElf => nameof(UnitRace.NightElf),
        UnitRace.Undead => nameof(UnitRace.Undead),
        UnitRace.Tauren => nameof(UnitRace.Tauren),
        UnitRace.Gnome => nameof(UnitRace.Gnome),
        UnitRace.Troll => nameof(UnitRace.Troll),
        UnitRace.Goblin => nameof(UnitRace.Goblin),
        UnitRace.BloodElf => nameof(UnitRace.BloodElf),
        UnitRace.Draenei => nameof(UnitRace.Draenei),
        UnitRace.FelOrc => nameof(UnitRace.FelOrc),
        UnitRace.Naga => nameof(UnitRace.Naga),
        UnitRace.Broken => nameof(UnitRace.Broken),
        UnitRace.Skeleton => nameof(UnitRace.Skeleton),
        UnitRace.Vrykul => nameof(UnitRace.Vrykul),
        UnitRace.Tuskarr => nameof(UnitRace.Tuskarr),
        UnitRace.ForestTroll => nameof(UnitRace.ForestTroll),
        UnitRace.Taunka => nameof(UnitRace.Taunka),
        UnitRace.NorthrendSkeleton => nameof(UnitRace.NorthrendSkeleton),
        UnitRace.IceTroll => nameof(UnitRace.IceTroll),
        UnitRace.Worgen => nameof(UnitRace.Worgen),
        UnitRace.GilneanHuman => nameof(UnitRace.GilneanHuman),
        UnitRace.Pandaren1 => nameof(UnitRace.Pandaren1),
        UnitRace.Pandaren2 => nameof(UnitRace.Pandaren2),
        UnitRace.Pandaren3 => nameof(UnitRace.Pandaren3),
        UnitRace.Nightborne => nameof(UnitRace.Nightborne),
        UnitRace.HighmountainTauren => nameof(UnitRace.HighmountainTauren),
        UnitRace.VoidElf => nameof(UnitRace.VoidElf),
        UnitRace.LightforgedDraenei => nameof(UnitRace.LightforgedDraenei),
        UnitRace.ZandalariTroll => nameof(UnitRace.ZandalariTroll),
        UnitRace.KulTiran => nameof(UnitRace.KulTiran),
        UnitRace.ThinHuman => nameof(UnitRace.ThinHuman),
        UnitRace.DarkIronDwarf => nameof(UnitRace.DarkIronDwarf),
        UnitRace.Vulpera => nameof(UnitRace.Vulpera),
        UnitRace.MagharOrc => nameof(UnitRace.MagharOrc),
        UnitRace.Mechagnome => nameof(UnitRace.Mechagnome),
        UnitRace.Dracthyr1 => nameof(UnitRace.Dracthyr1),
        UnitRace.Dracthyr2 => nameof(UnitRace.Dracthyr2),
        _ => nameof(UnitRace.None)
    };
}